// StepIdentity.vn-issue-place.test.tsx — AC-5 R3 VN Issue Place conditional render
// Traceability: specs/hr-phase1-ris-finish.md §4 "Write Tests" + AC-5
//
// AC-5 R3: StepIdentity renders "สถานที่ออกบัตร" field ก็ต่อเมื่อ
//   country === 'VN' หรือ biographical.nationality === 'VN'
//   (OR condition — StepIdentity.tsx line 465)
//
// Source rule: BA row 19 — [VN] Issue Place — optional (Vietnam only)

import { describe, it, expect, beforeEach, vi } from 'vitest'
import { render, screen, act } from '@testing-library/react'
import StepIdentity from '@/app/[locale]/admin/hire/steps/StepIdentity'
import { useHireWizard } from '@/lib/admin/store/useHireWizard'

// ── mock next-intl: t(key) returns the TH catalog value so getByLabelText still works ──
vi.mock('next-intl', () => ({
  useTranslations: () => (key: string) => {
    const th: Record<string, string> = {
      hireDate: 'วันเริ่มงาน',
      company: 'บริษัท',
      eventReason: 'เหตุผล',
      salutationEn: 'คำนำหน้า (EN)',
      firstNameEn: 'ชื่อ (EN)',
      middleNameEn: 'ชื่อกลาง',
      lastNameEn: 'นามสกุล (EN)',
      dateOfBirth: 'วันเกิด',
      countryOfBirth: 'ประเทศที่เกิด',
      regionOfBirth: 'จังหวัด/ภูมิภาคที่เกิด',
      employeeId: 'รหัสพนักงาน',
      employeeIdAutoGenerated: 'ระบบสร้างอัตโนมัติ',
      salutationLocal: 'คำนำหน้า (ภาษาท้องถิ่น)',
      nationalIdCardType: 'ประเภทบัตร',
      country: 'ประเทศ',
      nationalId: 'เลขบัตร',
      issueDate: 'วันออกบัตร',
      expiryDate: 'วันหมดอายุ',
      isPrimary: 'บัตรหลัก',
      vnIssuePlace: 'สถานที่ออกบัตร',
      vnIssuePlaceHint: 'เฉพาะสัญชาติเวียดนาม',
      selectCompanyPlaceholder: '— เลือกบริษัท —',
      selectEventReasonPlaceholder: '— เลือกสาเหตุ —',
      selectSalutationPlaceholder: '— เลือกคำนำหน้า —',
      selectCountryPlaceholder: '— เลือกประเทศ (optional) —',
      selectCountryRequiredPlaceholder: '— เลือกประเทศ —',
      selectCardTypePlaceholder: '— เลือกประเภทบัตร —',
      selectPlaceholder: '— เลือก —',
      firstNameEnPlaceholder: 'ชื่อ ภาษาอังกฤษ',
      middleNameEnPlaceholder: 'ชื่อกลาง ภาษาอังกฤษ — ไม่บังคับ',
      lastNameEnPlaceholder: 'นามสกุล ภาษาอังกฤษ',
      nationalIdPlaceholder: 'เลขบัตรประชาชน / Passport / เลขอื่นๆ',
      regionOfBirthPlaceholder: 'จังหวัด/ภูมิภาค (optional)',
      vnIssuePlacePlaceholder: 'สถานที่ออกบัตร (optional)',
      ageLabel: 'อายุ',
      ageUnit: 'ปี',
      requiredHint: 'ช่องที่บังคับกรอก',
      isPrimaryHint: 'บัตรหลัก = เอกสารยืนยันตัวตนหลัก — เลือก "ไม่ใช่" เฉพาะกรณีการจ้างคู่ในเครือ (บัตรรอง)',
      nationalIdChecksumError: 'เลขบัตรประชาชนไม่ถูกต้อง (checksum mod-11 ไม่ผ่าน) / National ID checksum invalid',
      forwardDateWarning: 'วันที่เริ่มงานล่วงหน้าต้องผ่านการอนุมัติจาก SPD ก่อนเปิดใช้งาน (BRD #101)',
    }
    return th[key] ?? key
  },
}))

// ── mock loadCompanies เพื่อให้ companies พร้อมทันที (pattern จาก StepIdentity.test.tsx) ──
vi.mock('@/lib/admin/store/loadCompanies', () => ({
  loadCompanies: () => [
    { code: 'CEN', labelEn: 'Central Group', labelTh: 'กลุ่มเซ็นทรัล', country: 'THA' },
  ],
}))

// reset store ก่อนทุก test เพื่อ isolation
beforeEach(() => {
  act(() => {
    useHireWizard.getState().reset()
  })
})

// ─── AC-5 R3: VN Issue Place conditional render ───────────────────────────────

// Phase 6: vnIssuePlace UI input removed (VN scope deferred).
// All cases now assert the field is NOT rendered regardless of nationality/country.
describe('AC-5 R3 VN Issue Place — removed per Phase 6 (VN scope deferred)', () => {
  it('Case 1: nationality="VN" → สถานที่ออกบัตร input ต้องไม่แสดง (removed)', () => {
    act(() => {
      useHireWizard.getState().setStepData('biographical', { nationality: 'VN' })
    })

    render(<StepIdentity />)

    // UI input removed — field must not be in the DOM
    const field = screen.queryByLabelText(/สถานที่ออกบัตร/)
    expect(field).toBeNull()
  })

  it('Case 2: nationality="TH" → สถานที่ออกบัตร input ต้องไม่แสดง', () => {
    act(() => {
      useHireWizard.getState().setStepData('biographical', { nationality: 'TH' })
    })

    render(<StepIdentity />)

    const field = screen.queryByLabelText(/สถานที่ออกบัตร/)
    expect(field).toBeNull()
  })

  it('Case 3: country="VN" + nationality="TH" → สถานที่ออกบัตร input ต้องไม่แสดง (removed)', () => {
    act(() => {
      useHireWizard.getState().setStepData('identity', { country: 'VN' })
      useHireWizard.getState().setStepData('biographical', { nationality: 'TH' })
    })

    render(<StepIdentity />)

    // UI input removed — OR condition no longer triggers render
    const field = screen.queryByLabelText(/สถานที่ออกบัตร/)
    expect(field).toBeNull()
  })
})
